org.acme.openapi.faulttolerance.api.DefaultApi/withCircuitBreakerGet/CircuitBreaker/enabled=true
org.acme.openapi.faulttolerance.api.DefaultApi/withCircuitBreakerGet/CircuitBreaker/failOn = java.lang.IllegalArgumentException,java.lang.NullPointerException
org.acme.openapi.faulttolerance.api.DefaultApi/withCircuitBreakerGet/CircuitBreaker/skipOn = java.lang.NumberFormatException, java.lang.IndexOutOfBoundsException
org.acme.openapi.faulttolerance.api.DefaultApi/withCircuitBreakerGet/CircuitBreaker/delay = 33
org.acme.openapi.faulttolerance.api.DefaultApi/withCircuitBreakerGet/CircuitBreaker/delayUnit = MILLIS
org.acme.openapi.faulttolerance.api.DefaultApi/withCircuitBreakerGet/CircuitBreaker/requestVolumeThreshold = 42
org.acme.openapi.faulttolerance.api.DefaultApi/withCircuitBreakerGet/CircuitBreaker/failureRatio = 3.14
org.acme.openapi.faulttolerance.api.DefaultApi/withCircuitBreakerGet/CircuitBreaker/successThreshold = 22

org.acme.openapi.faulttolerance.api.DefaultApi/withTimeoutGet/Timeout/enabled=true

org.acme.openapi.faulttolerance.api.DefaultApi/withRetryGet/Retry/enabled=true

org.acme.openapi.faulttolerance.api.DefaultApi/withTimeoutRetryAndCircuitBreakerGet/Timeout/enabled=true
org.acme.openapi.faulttolerance.api.DefaultApi/withTimeoutRetryAndCircuitBreakerGet/Retry/enabled=true
org.acme.openapi.faulttolerance.api.DefaultApi/withTimeoutRetryAndCircuitBreakerGet/CircuitBreaker/enabled=true

quarkus.keycloak.devservices.enabled=false

quarkus.openapi-generator.codegen.spec.fault_tolerance_openapi_json.base-package=org.acme.openapi.faulttolerance